### ISSUE TITLE
Consider not embedding referenced assemblies

### ISSUE THREAD

**Issue by milang** [pandell/PackageRunner#2]
Because NuGet packages can contain more than one file, we should be fine keeping referenced assemblies in the same directory as the `PackageRunner.exe`, and updating when when needed.

Even better would be to use the dependencies feature, so that e.g. `NuGet.Core` assembly would be brought in via its package, not be directly included in `PackageRunnert`. This would make `PackageRunner` NuGet package smaller and faster to update (this idea is similar to how `npm` works in `node.js`).

**Comment by tenkod** [comment]
The reasons the assemblies are embedded and set to specific version are:
1. NuGet Core latest source was significantly different from the library version we are using (ie. it would behave differently if updated. And we are not using some hacks or hidden features it simply is evolving in different direction. So pretty much we don't need updates there).
2. It would simplify deployment to just one file.
3. NuGet core is needed for auto-update functionality so we can't go without it from the start.

**Comment by milang** [comment]
Reason 3 makes sense.

In any case please remove `Microsoft.Web.XmlTransform`, it is not needed. If a package installed by `PackageRunner` needs it, it should install it instead of relying to `PackageRunner` to provide it.

**Comment by tenkod** [comment]
`Microsoft.Web.XmlTransform` it's the only assembly not included in .Net installation needed by `NuGet.Core`.

**Comment by milang** [comment]
Makes sense, closing.
